#!/bin/sh
x=${1%%.*}
echo $x
echo ./c2go.py $x.c \> $x.go
./c2go.py $x.c > $x.go
rm lextab.py yacctab.py
echo gofmt -w $x.go
gofmt -w $x.go
echo 6g $x.go
6g $x.go
echo 6l -o $x $x.6 && echo ok
6l -o $x $x.6 && rm $x.6
